/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as PracticeAreasIndexRouteImport } from './routes/practice-areas.index'
import { Route as PracticeAreasSlugRouteImport } from './routes/practice-areas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasIndexRoute = PracticeAreasIndexRouteImport.update({
  id: '/practice-areas/',
  path: '/practice-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreasSlugRoute = PracticeAreasSlugRouteImport.update({
  id: '/practice-areas/$slug',
  path: '/practice-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/practice-areas': typeof PracticeAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice-areas/$slug': typeof PracticeAreasSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/practice-areas/': typeof PracticeAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/why-choose-us'
    | '/insights/$slug'
    | '/practice-areas/$slug'
    | '/insights/'
    | '/practice-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/why-choose-us'
    | '/insights/$slug'
    | '/practice-areas/$slug'
    | '/insights'
    | '/practice-areas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/why-choose-us'
    | '/insights/$slug'
    | '/practice-areas/$slug'
    | '/insights/'
    | '/practice-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  PracticeAreasSlugRoute: typeof PracticeAreasSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PracticeAreasIndexRoute: typeof PracticeAreasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/': {
      id: '/practice-areas/'
      path: '/practice-areas'
      fullPath: '/practice-areas/'
      preLoaderRoute: typeof PracticeAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-areas/$slug': {
      id: '/practice-areas/$slug'
      path: '/practice-areas/$slug'
      fullPath: '/practice-areas/$slug'
      preLoaderRoute: typeof PracticeAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  PracticeAreasSlugRoute: PracticeAreasSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PracticeAreasIndexRoute: PracticeAreasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
